name: Python Quality Check
on: [push]

jobs:
  verify-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Linting Tool
        run: pip install flake8

      - name: Check for Syntax Errors
        # This will fail the "build" if there are Python syntax errors
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics